### ISSUE TITLE
Starting Simple Cryptography

### ISSUE THREAD

**Issue by TetroVolt** [xylafur/DataStructures#10]
Planning to add for now:
- Vigenere Cipher
- Caesar Cipher

Possibly in the future
- Xor ciphers
- RSA ciphers

**Comment by xylafur** [comment]
Hey man don't forget to assign yourself to issues you are working on.

**Comment by techmexdev** [comment]
yeah dude

**Comment by TetroVolt** [comment]
Closed project because Cryptography is not a data structure. Possible plans on library repository

**Comment by techmexdev** [comment]
lols
