### ISSUE TITLE
Making Double Linked List Class

### ISSUE THREAD

**Issue by xylafur** [xylafur/DataStructures#2]
Creating a double linked list class using my double linked list node

**Comment by TetroVolt** [comment]
You cant overload member variables. Its legal to do so but it just hides the super class variable. Memory is still being allocated for it tho.

**Comment by TetroVolt** [comment]
[here](https://bytes.com/topic/c/answers/704995-possible-overload-member-variable)

**Comment by xylafur** [comment]
It should still function though yes?  It seems that the only downside is that there is some memory being wasted.

**Comment by xylafur** [comment]
Turns out that this was a problem so i ended up ditching inheritance because it didnt make sense with different types of nodes.
