### ISSUE TITLE
Working on implementing indexOf capability for Lists/ArrayList

### ISSUE THREAD

**Issue by TetroVolt** [xylafur/DataStructures#9]
Considerations:
- Do comparison operators work for Template classes?

**Comment by xylafur** [comment]
If the comparison operator is defined for whatever type you are using then yes it will work.  If you use a custom object just ensure that you have overloaded the comparison operators.

**Comment by xylafur** [comment]
Oh and don't forget to assign yourself to your tasks

**Comment by TetroVolt** [comment]
Finished cheap implementation of sequential search for indexOf and contains
